<?php


function test_form_menu(){
  $items = array();

  $items['test_form'] = array(
    'title' => 'Page title',
    'page callback' => 'test_form_callback',
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE, 
  );

  return $items;
}

function test_form_callback() {
  $form_1=drupal_get_form('test_form_form');
  $form_1=drupal_render($form_1);

    return ($form_1);
}


function test_form_form($form, &$form_state){
    $form = array();
    $form['name'] = array(
      '#type' => 'textfield',
      '#title' => t('Your name'),
      '#required' => TRUE,
    );
    $form['settings'] = array(
      '#type' => 'radios',
      '#title' => t('Your sex'),
      '#options' => array(0 => t('Man'), 1 => t('Woman')),
      '#description' => t('Select your sex.'),
      '#required' => TRUE,
    );
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Submit'),
    );
    return $form;
  }


function test_form_form_validate($form, &$form_state)
{   if (drupal_strlen($form_state['values']['name']) < 3) {
        form_set_error('name', t('Your name is very short.'));
    }
}

function test_form_form_sumbit($form, &$form_state)
{
    variable_set('my_name', $form_state['values']['name']);
    variable_set('my_sex', $form_state['values']['sex']);
    drupal_set_message(t('Your data saved'));
}