<?php

function custom_test_module_menu() {
  $items = array();

  $items['customtest'] = array( // рут с формой
    'title' => 'Тестовая Анкета',
    'page callback' => array('drupal_get_form'),
    'page arguments' => array('custom_test_module_form','W1'),
    'access arguments' => array('access content'),
  );

  $items['theme_render'] = array( // рут с theme_render_template 
    'title' => 'Анкета с шаблоном',
    'page callback' => array('custom_test_module_theme_render_callback'),
    'access arguments' => array('access content'),
  );

  return $items;
}

function custom_test_module_form($form, &$form_state)
{

   
  $form['title_second_name'] = array( // Ф

    '#type' => 'textfield', 
    '#title' => 'Фамилия',
    '#size' => 30, 
    '#maxlength' => 128, 
  );
  
  $form['title_first_name'] = array(// И

    '#type' => 'textfield', 
    '#title' => 'Имя', 
    '#size' => 30, 
    '#maxlength' => 128, 
  );
  
  $form['title_third_name'] = array(// О

    '#type' => 'textfield', 
    '#title' => 'Отчество', 
    '#size' => 30, 
    '#maxlength' => 128, 
  );

  $form['phonenumber'] = array( // номер телефона
    '#type' => 'textfield',
    '#attributes' => array(
        'data-type' => 'number',
    ),
    '#title' => 'Номер телефона (+7...)',
    '#maxlength' => 10 ,
    '#field_prefix'=> '+7',
    '#size'=> 10,
    
  );

  $form['sex_radios'] = array( // radiobutton с полом
    '#type' => 'radios',
    '#title' => 'Укажите пол',
    '#options' => array('male' => 'Мужской', 'female' => 'Женский'),
    
  );

  $form['e_mail'] = array(// email

    '#type' => 'textfield', 
    '#title' => 'Email', 
    '#size' => 30, 
    '#maxlength' => 128, 
  );

  $form['e_mail'] = array(// email

    '#type' => 'textfield', 
    '#title' => 'Email', 
    '#size' => 30, 
    '#maxlength' => 128, 
  );


  $form['list_choice'] = array( // список да/нет для подтверждения уведомлений
    '#type' => 'select',
    '#title' => 'Хотите получать уведомления на п/я?',
    '#options' => array(
      1 => 'Да',
      0 => 'Нет',    
    ),
    
  );

  $form['list_choice'] = array( // список да/нет для подтверждения уведомлений
    '#type' => 'select',
    '#title' => 'Хотите получать уведомления на п/я?',
    '#options' => array(
      1 => 'Да',
      0 => 'Нет',    
    ),
  );

  $terms_of_use_text = 'Нажимая кнопку «Продолжить», 
  я принимаю условия Пользовательского соглашения, даю своё согласие "xxx" 
  и БАНК 
  на обработку моих персональных данных в соответствии с Федеральным законом 
  от 27.07.2006 года №152-ФЗ «О персональных данных» на условиях и для целей, 
  определенных Политикой конфиденциальности, на передачу персональных данных от ООО xxx 
  Банку, а также соглашаюсь на получение рекламы от Банка и xxx по сетям электросвязи
  с соответствии с частью 1 статьи 18 Федерального закона от 13.03.2006 №38-ФЗ
  «О рекламе» на условиях Пользовательского соглашения.';

  $form['terms_of_use_text'] = array( //текст поле с условиями пользования 
    '#title' => 'Условия пользования',
    '#prefix' => '<br><br><br><br>',
    '#type' => 'fieldset',
    '#description' => $terms_of_use_text,
  );

  $form['terms_of_use_checkbox'] = array(// чекбокс для условий пользования
    '#type' => 'checkbox', 
    '#title' => 'Я согласен с условиями пользования ...',
  );

  $form['next_button'] = array( // кнопка продолжить
    '#type' =>'submit', 
    '#value' => 'Продолжить', 
  );
  
  return $form;
}

function custom_test_module_form_validate($form, &$form_state)
{   

  if (!empty($form_state['values']['phonenumber'])) { // проверка факта наличия номера телефона и его корректности по длине  
    if (strlen($form_state['values']['phonenumber']) < 10){
      form_set_error('phonenumber', 'Укажите номер телефона полностью!');}
    if (!preg_match("/^(\d){1,10}$/" ,($form_state['values']['phonenumber']))){
      form_set_error('phonenumber', 'Укажите цифровое значение!');}
    } else {
      form_set_error('phonenumber', 'Укажите номер телефона!');
    }
  ;
  
    
  if (!empty($form_state['values']['title_second_name'])){ // проверка факта наличия указанного ФИО + заглавной буквы 
    if (!preg_match("/^[A-Z]{1}[a-z]{1,}/", ($form_state['values']['title_second_name']))) 
    {
      form_set_error('title_second_name', 'Укажите Фамилию с заглавной буквы, английскими символами, без пробелов!');
    }
  } else {
      form_set_error('title_second_name', 'Укажите Фамилию!');
  } 
  
  
  // empty 1 слово 

  if (!empty($form_state['values']['title_first_name'])){
    if (!preg_match("/[а-яё][\s][а-яё]/iu", ($form_state['values']['title_first_name']))) 
    {
      form_set_error('title_first_name', 'Укажите Имя в два слова, русскими символами, через пробел!');
    }
  } else {
    form_set_error('title_first_name', 'Укажите Имя!');   
  }
  // два слова 

  if (!empty($form_state['values']['title_third_name'])){
    if (!preg_match("/^[А-ЯЁ]{1}[а-яё]{1,}/", ($form_state['values']['title_first_name']))) 
    {
      form_set_error('title_third_name', 'Укажите Отчество с заглавной буквы, русскими символами, без пробелов!');
    } 
  }
  // русское 

  if (empty($form_state['values']['sex_radios'])) { // проверка факта наличия указанного пола 
    form_set_error('sex_radios', 'Укажите ваш пол!');
  }

  if (($form_state['values']['terms_of_use_checkbox']) != 1){ // проверка факта наличия галочки 
    form_set_error('terms_of_use_checkbox','Требуется согласие с условиями пользования!');
  }; 
 
}

function custom_test_module_form_submit($form, &$form_state)
{
  $title_second_name=$form_state['values']['title_second_name'];
  $title_first_name=$form_state['values']['title_first_name'];
  $title_third_name= $form_state['values']['title_third_name'];
  $sex=$form_state['values']['sex_radios'];
  $phonenumber=$form_state['values']['phonenumber'];
  $list_choice=$form_state['values']['list choice'];
  
  variable_set('title_second_name', $title_second_name);
  variable_set('title_first_name', $title_first_name);
  variable_set('title_third_name', $title_third_name);
  variable_set('phonenumber', $phonenumber);
  variable_set('list_choice', $list_choice);
  variable_set('sex', $sex);

  
  drupal_set_message('Продолжаем '.$title_first_name.' '.$title_second_name);
}


function custom_test_module_theme_render_callback()
{

  $variables=[
    'name'=> 'Max',
    'age' => 27,
  ];
  return  theme_render_template(path_to_theme() . '/custom_page.tpl.php', $variables);
}

