<?php

define('REG_DESCRIPTION', [
  'ИП' => 'P21001',
  'ООО' => 'P11001',
  'ИзмИП' => 'P24001',
  'ИзмООО' => 'P13014'
]);

module_load_include('inc', 'b_stats', 'b_stats.faker');

function b_stats_menu()
{
  $items = array();

  $items['stats'] = array(
    'title' => 'Статистика заявок',
    'page callback' => array('b_stats_theme_render_callback'),
    'access arguments' => array('access content'),
  );

  $items['full_stats'] = array(
    'title' => 'Полная статистика заявок',
    'page callback' => array('b_stats_full_theme_render_callback'),
    'access arguments' => array('access content'),
  );

  return $items;
}

function b_stats_theme_render_callback()
{
  $content = b_stats_faker_statistics_generator(rand(3, 8));

  $content = [
    'main_data_list' => prepare_main_data_list($content)
  ];

  return theme_render_template('sites/all/modules/custom/b_stats/theme/main.tpl.php', $content);
}

function b_stats_full_theme_render_callback()
{
  $content = b_stats_faker_statistics_generator(rand(3, 8));

  $content = [
    'full_data_list' => prepare_full_data_list($content)
  ];

  return theme_render_template('sites/all/modules/custom/b_stats/theme/full.tpl.php', $content);
}

function prepare_full_data_list($list)
{
  $result_array = [];
  foreach ($list as $record) {

    if ($record['Sex'] == 'male') {
      $sex_data = 'Мужской';
    } elseif ($record['Sex'] == 'female') {
      $sex_data = 'Женский';
    } else {
      $sex_data = '-';
    }

    $record_array =
      [
        'main_info' =>
        [
          'title' => 'Основная информация',
          'value' =>
          [
            'id' => [
              'col' => 'ID',
              'val' => $record['ID']
            ],

            'full_name' => [
              'col' => 'ФИО',
              'val' => implode(' ', array_filter([$record['First_name'], $record['Second_name'], $record['Third_name']]))
            ],

            'inn' => [
              'col' => 'ИНН',
              'val' => $record['Inn']
            ],

            'email' => [
              'col' => 'Email',
              'val' => $record['Email']
            ]
          ]
        ],
        'extra_info' =>
        [
          'title' => 'Дополнительная информация',
          'value' =>
          [
            'phone_number' => [
              'col' => 'Номер телефона',
              'val' => $record['Phone']
            ],

            'reg_form' => [
              'col' => 'Форма регистрации',
              'val' => ((array_search($record['Reg_form'], REG_DESCRIPTION)) ?: '-')
            ],

            'snils' => [
              'col' => 'СНИЛС',
              'val' => $record['Snils']
            ],

            'birthday' => [
              'col' => 'Дата рождения',
              'val' => $record['Bday']
            ],

            'sex' => [
              'col' => 'Пол',
              'val' => $sex_data
            ],

            'address' => [
              'col' => 'Адрес',
              'val' => $record['Address']
            ]
          ]
        ]
      ];
    $result_array[$record['ID']] = $record_array;
  }
  return $result_array;
}

function prepare_main_data_list($list)
{
  return (array_map((function ($record) {
    return [
      'id' => [
        'col' => 'ID',
        'val' => $record['ID']
      ],

      'full_name' => [
        'col' => 'ФИО',
        'val' => implode(' ', array_filter([$record['First_name'], $record['Second_name'], $record['Third_name']]))
      ],

      'inn' => [
        'col' => 'ИНН',
        'val' => $record['Inn']
      ],

      'email' => [
        'col' => 'Email',
        'val' => $record['Email']
      ],

      'phone_number' => [
        'col' => 'Номер телефона',
        'val' => $record['Phone']
      ],

      'reg_form' => [
        'col' => 'Форма регистрации',
        'val' => ((array_search($record['Reg_form'], REG_DESCRIPTION)) ?: '-')
      ]
    ]; }), $list));
}