<?php

module_load_include('inc', 'b_stats', 'b_stats.faker');

function b_stats_menu() {
  $items = array();

  $items['stats'] = array( 
    'title' => 'Статистика заявок',
    'page callback' => array('b_stats_theme_render_callback'),
    'access arguments' => array('access content'),);

  return $items;
}

function b_stats_theme_render_callback(){
  $content=['data_list' => b_stats_faker_statistics_generator(rand(10,35))];
  return theme_render_template('sites/all/modules/custom/b_stats/theme/main.tpl.php', $content);
}